name: Install/Update TeXLive
runs:
  using: composite
  steps:
    - name: Setup TeXLive
      uses: teatimeguest/setup-texlive-action@v3
      with:
        packages: scheme-full
        update-all-packages: true
