name: Build
on:
  workflow_dispatch:
  push:
    branches: [ main ]
jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: thesis
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Install TeX Live
        uses: zauguin/install-texlive@v2
        with:
          packages: scheme-small
#      - name: Build Thesis
#        run: arara --verbose main
#      - name: Upload Artifact
#        uses: actions/upload-artifact@v3
#        with:
#          name: thesis
#          path: tuda_logo.pdf
#          if-no-files-found: error
#  publish:
#    name: Publish
#    runs-on: ubuntu-latest
#    needs: build
#    permissions: {}
#    steps:
#      - name: Download Artifact
#        uses: actions/download-artifact@v3
#        with:
#          name: thesis
#      - name: Send Telegram Notification
#        uses: appleboy/telegram-action@master
#        with:
#          to: ${{ secrets.TELEGRAM_TO }}
#          token: ${{ secrets.TELEGRAM_TOKEN }}
#          message: A fresh version of your thesis was created!
#          document: thesis/main.pdf
