name: Build
on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - "thesis/**"
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          lfs: true
      - uses: ./.github/actions/texlive
      - name: Build Thesis
        run: "arara --verbose main"
        working-directory: ./thesis
      - name: Move Compilation to Pages
        run: "mv thesis/main.pdf _site/latest.pdf"
      - name: Upload GitHub Pages Artifact
        uses: actions/upload-pages-artifact@v3
# use the following to actually deploy the GitHub page (note that this must be
# enabled in the repository's settings)
#  deploy:
#    name: Deploy
#    runs-on: ubuntu-latest
#    permissions:
#      id-token: write
#      pages: write
#    needs:
#      - build
#    steps:
#      - name: Deploy to GitHub Pages
#        uses: actions/deploy-pages@v4
