name: Install/Update TeXLive
on:
  workflow_call:
  workflow_dispatch:
jobs:
  install:
    name: Install and Update
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - uses: ./.github/actions/texlive
