name: Install/Update TeXLive
on:
  workflow_call:
  workflow_dispatch:
jobs:
  install:
    name: Install and Update
    runs-on: ubuntu-latest
    steps:
      - name: Setup TeXLive
        uses: teatimeguest/setup-texlive-action@v2
        with:
          packages: scheme-minimal
          update-all-packages: true
